[project]
name = "maestro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nayfusaurus", email = "35911760+nayfusaurus@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "mido>=1.3.3",
    "pynput>=1.8.1",
]

[project.scripts]
maestro = "maestro:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
